### ISSUE TITLE
Next issue: July 2019

### ISSUE THREAD

**Issue by nrc** [nrc/tmit#3]
Comment if you have things that should be covered in this issue. Please leave a link.

Since this is the first issue, we should cover anything that has happened in the past few months.

**Comment by nrc** [comment]
* TiDB 3.0 release and accompanying TiKV release
* Jepsen report
* Rust client ongoing work
* Compile time improvements

**Comment by nrc** [comment]
Blog posts:

* Client futures migration: https://www.ncameron.org/blog/migrating-a-crate-from-futures-0-1-to-0-3/
* benchmarking a dist DB: https://www.pingcap.com/blog/why-benchmarking-distributed-databases-is-so-hard/

**Comment by dcalvin** [comment]
I think by the end of July we should have finished migrating our docs from the tikv Wiki to tikv.org.
We should definitely let folks know if we **achieve that**.

**Comment by siddontang** [comment]
I think we should also show the progress of backup/restore demo.

**Comment by nrc** [comment]
Plans for 4.0

**Comment by siddontang** [comment]
can choose protobuf and prost?

**Comment by dcalvin** [comment]
We are already directing users to our new site for documentation. I think you can mention this in the Monthly. 

 Quote from Readme:

> We are currently migrating our documentation from the [TiKV's wiki page](https://github.com/tikv/tikv/wiki/) to the [official website](https://tikv.org/docs). We'd appreciate if you could check out the new look on the website and offer your feedback [here](https://github.com/tikv/website). The Wiki page will be discontinued when the migration is finished. Stay tuned!

**Comment by nrc** [comment]
I want to have a section on 'interesting work in progress' I propose the following:

* prost migration 
* new docs site https://tikv.org/docs/3.0/concepts/overview/
* performance
* better testing and stability - long-running tests
* production-ready titan
* adding RPN functions
* backup/restore
* follower/learner read
* joint consensus
* production-ready pessimistic transactions

I want to check that all of this is ok to talk about publicly - @siddontang ?

I also don't know enough about the following to write anything:

- [ ] production-ready titan 
- [x] adding RPN functions 
- [ ] backup/restore
- [x] follower/learner read
- [ ] joint consensus
- [ ] production-ready pessimistic transactions

I think we need only three sentences for each: what it is. Why it is awesome. Status/what is being worked on. Please can people write these for me?

**Comment by siddontang** [comment]
titan and pessimistic transaction are not production-ready. although titan has been run in one big company for a long time, we still think we need to test it for some time before releasing it. 

the previous backup is deprecated, and joint consensus has no any update.

so here, we can talk about RPN and follower/learner read.

**Comment by nrc** [comment]
> titan and pessimistic transaction are not production-ready. although titan has been run in one big company for a long time, we still think we need to test it for some time before releasing it.

these sections are meant to describe work which is in-progress, not work which is finished, so the goals here are to make them production-ready, not assuming that they already are.

I think it is nice to talk about exciting work which is happening, even if there is not much progress.

**Comment by Hoverbear** [comment]
@siddontang It's okay to talk about in development features, and titan was already released in 3.0 as stable.

**Comment by nrc** [comment]
maybe I should describe it as "improvements to ..." instead of "production-ready"

**Comment by 5kbpers** [comment]
@nrc Follower/Learner Read (Maybe we shall call it Replica Read) enable TiKV to execute read command on Replicas. 
It can relieve the pressure of hot spot Leaders, accelerate read command execution when the client is far from Leader but is close to a Follower. It supports SI and linearizability in txn mode, but would hurt linearizability in raw mode. 
This function has already merged to TiKV master, can be enabled through an RPC option. We are working on supporting it in TiDB.
Do I need to write a more detailed doc? :)

**Comment by breezewish** [comment]
This month we supported the following function to be used in batch execution:
- coalesce
- in
- case_when
- if
- abs
- multiply
- divide
- date_format

**Comment by nrc** [comment]
Closed - issue added
